# Generated by Django 2.2.6 on 2019-10-31 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_hits'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('session', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrlHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('hit', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Hits',
        ),
        migrations.AddField(
            model_name='hitcount',
            name='url_hit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UrlHit'),
        ),
    ]
